module.exports = {
  plugins: [
    require('tailwindcss'),
    require('autoprefixer'),
    // purgecss({
    //   content: ['./**/*.js'],
    //   whitelist: [
    //     'lg:flex-row',
    //     'lg:mt-32',
    //     'lg:items-center',
    //     'lg:justify-center',
    //     'lg:h-100vh',
    //     'lg:w-1/2',
    //     'lg:w-full',
    //     'lg:text-xl',
    //     'sm:px-4',
    //     'sm:w-1/2',
    //     'sm:mx-auto',
    //     'lg:mx-0',
    //     'lg:ml-5',
    //     'sm:mr-20',
    //     'sm:w-1/3',
    //     'sm:mx-1',
    //     'md:mx-3',
    //     'lg:w-1/5',
    //     '',
    //     '',
    //     '',
    //     '',
    //     '',
    //     '',
    //     '',
    //   ],
    // }),
    // require('postcss-preset-env')({
    //   stage: 0,
    //   autoprefixer: {
    //     // grid: true,
    //   },
    //   preserve: false,
    // }),
  ],
};
